### ISSUE TITLE
cannot build disp_driver.c

### ISSUE THREAD

**Issue by KammutierSpule** [littlevgl/lv_port_esp32#105]
**Describe the issue**

Cannot build

**Compilation warnings/errors (if available)**
../components/lvgl_esp32_drivers/lvgl_tft/disp_driver.c:20:5: error: implicit declaration of function 'ili9341_init';

It looks it is adding this file and it shouldn't? because disp_driver.c is inline included in lvgl_driver.c

**Comment by C47D** [comment]
Hi,

Are you selecting a predefined display configuration on the menuconfig or selecting every option by yourself? I'm working with the Wrover Kit v4.1 preconfiguration (it have the ILI9341 display controller) and i can't reproduce the issue.

**Comment by KammutierSpule** [comment]
I'm assigning the PINs myself on the "Display Pin Assignments"
The predefined options are set to "None"
but I should note that CONFIG_LVGL_TFT_DISPLAY_CONTROLLER_ILI9341 is set
so this issues is because that .c file is included and there is no include to this define.
but I think thats ok because it should be excluded from the build list? ..

**Comment by KammutierSpule** [comment]
I found the issue, It was my fault! I deleted by mistake the includes that are need to this esp32 port in the config.h

**Comment by C47D** [comment]
Don't worry, happy to know you solved it.
